version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ecommerce
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: huydoged
      MONGO_INITDB_ROOT_PASSWORD: 0995538418a
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data:
    driver: local
